
-- THIS COMMAND IS USED TO CREATE A TABLE OR DATABASE
-- WHEN CREATING A TABLE MAKE SURE AFTER TWO CLAUE (CREATE TABLE) IT'S TABLE NAME
-- e.g CREATE  TABLE table_name
-- THE ABOVE SCRIPT IS FOLLLOWED BY TWO BRACKETS CLOSE AND OPEN BRACKET
-- e.g CREATE TABLE table_name();
-- WHAT YOU MUST WRITE INSIDE ARE THE ATTRIBUTES, AND IT'S CONSTRAINT WHICH ARE THE RULES THAT MUST BE MET BY THE TABLE 
-- THEY MUST NOT BE VALUATED BY ALL MEANS 
-- e.g PRIMARY KEY 
-- FORIGN KEY
-- UNIQUE
-- NOT NULL
-- CHECK
-- INDEX

-- REMEMBER THAT THE DATA TYPE OF THE TABLE IS NOT A CONSTRAINT IT'S JUST A DIFINATION OF WHAT KIND OF THAT THAT COLUMN IS EXPECTING
-- e.g String, int, double, char,bool,date,blob
CREATE TABLE Customers(
CustomerID INT IDENTITY(1,1),
FirstName VARCHAR(50) NOT NULL,
LastName VARCHAR(50) NOT NULL,
Email VARCHAR(50) NOT NULL,
City VARCHAR(50) NOT NULL
PRIMARY KEY(CustomerID)
);