-- THIS COMMAND IS USED TO DELETE A RECORD IN A TABLE
-- RECORD : ROW
-- FOR EXAMPLE THIS ONE DELETES A ROW WITH EMPLOYEEID 10 OR A EMPLYEE WITH A PRIMARY KEY 10
DELETE FROM Employees 
WHERE EmployeeID = 
10

-- IF THE USER OF IF I OMIT THE PRIMARY KEY OR I DID'T SPECIFY WHICH ROW OR RECORD I WANT TO DELETE THE WHOLE COLUMN ROCORDS WILL BE DELTED
-- TO AVOID THIS MAKE SURE THAT YOU HAVE 'WHERE' CLAUSE WHICH IS THE FILTER CLAUSE
-- e.g THIS COMMAND WILL DELETE EVERY RECORD IN THE TABLE
DELETE FROM Customers
