-- THIS COMMAND CREATES TABLE 
-- IT DEFINES THE DATABASE MEANING IT DEFINES DATA TYPES OF THE ATTRIBUTES AND 
-- CONTRAINTS THAT MUST BE MET BY THE ENTITY OR BY THE TABLE
CREATE TABLE Customers(
CustomerID INT IDENTITY(1,1),
FirstName VARCHAR(50) NOT NULL,
LastName VARCHAR(50) NOT NULL,
Email VARCHAR(50) NOT NULL,
City VARCHAR(50) NOT NULL
PRIMARY KEY(CustomerID)
);

-- THIS IS THE SECOND TABLE WHICH IS THE CHILD OF THE CUSTOMER TABLE
-- THIS TABLE IS GOING HAVE A NEW KEY TYPE WHICH IS FOREIGN KEY THAT REFERENCES TO CUSTOMER TABLE, 
-- REFERENCING USING CUSTOMERID THAT IS IN THE CUSTOMER TABLE 
-- THIS TABLE MUST HAVE A ATTRIBUTE THAT IS GOING TO STORE THE PRIMARY KEY ITS PARENT WHICH IS THE CUSTOMER ID
CREATE TABLE Orders(
OrdersID INT IDENTITY(1,1),
CustomerID INT NOT NULL,
OrderDate DATE NOT NULL,
OrderPrice DECIMAL(10,2)
FOREIGN KEY(CustomerID) REFERENCES Customers(CustomerID),
-- THIS TABLE I DONT HAVE PRIMARY KEY 
-- I WILL USE ALTER TO INSERT IT
);
