-- THIS COMMAND IS SAME AS TOP BUT IT IS USED WITH ORDER BY COMMAND
SELECT * FROM Customers
ORDER BY FirstName 
OFFSET 17 ROWS FETCH NEXT 1 ROWS ONLY

-- THE FIRST COMMMAD 'OFFEST 17 ROWS' MEANS ROWS TO BE  SKIPPED
-- THE SECOND COMMAND 'FETCH NEXT 1 ROWS ONLY' MEANING RETURN 1 ROW TO BE RETURNED


