-- THIS COMMAND SELECTS EVERY COLUMNS OR IT RETIREVES EVERY INFO IN THE TABLE
SELECT * FROM Customers;

-- THIS COMMAND IS USED AS FILTER, BECAUSE THE USER IS ABLE TO SPECIFY WHAT KIND OF INFORMATION IS H/SHE IS WILLING TO RETURN
SELECT * FROM Customers
WHERE City = 'Johannesburg';

-- YOU CAN USE SELECT TO RETURN SPECIF COLUMNS IN A TABLE 
SELECT FirstName, LastName 
FROM Customers;

-- THIS COMMAND IS USED RETURN SPECIFIC NUMBER OR RECORDS IN TABLE
SELECT TOP 10  *
FROM Customers;

-- THIS COMMAND IS THE SAME AS THE ABOVE, THE DIFFERENCE IT USES THE PERCENTAGE TO RETURN CERTAIN COLUMNS
-- THIS COMMAND RETURNS 50% OF THE COLUMNS
SELECT TOP 50 PERCENT
FROM Customers;

