
-- THIS COMMAND UPADTES THE THE VALUES OF EACH RECORD 
-- YOU MUST NOT OMIT THE WHERE ELSE ALL THE RECORD WILL BE UPDATED FOR THE SPECIFIED COLUMN
UPDATE  Employees
SET Salary = 72500
WHERE EmployeeID = 9

-- THIS  WILL UPDATE ALL THE CITIES TO JOHANNESBURG
UPDATE sales.customers 
SET city = 'Johannesburg'
